/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Id = IDL.Text;
export const EssayTopic = IDL.Record({ 'id' : Id, 'title' : IDL.Text });
export const EssayModule = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'moduleType' : IDL.Text,
  'topics' : IDL.Vec(EssayTopic),
});
export const MCQ = IDL.Record({
  'id' : Id,
  'moduleId' : Id,
  'question' : IDL.Text,
  'explanation' : IDL.Text,
  'correctAnswer' : IDL.Text,
  'subjectId' : Id,
  'optionA' : IDL.Text,
  'optionB' : IDL.Text,
  'optionC' : IDL.Text,
  'optionD' : IDL.Text,
});
export const Module = IDL.Record({
  'id' : Id,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'subjectId' : Id,
});
export const Subject = IDL.Record({
  'id' : Id,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'color' : IDL.Text,
});

export const idlService = IDL.Service({
  'addEssayModule' : IDL.Func([IDL.Text, EssayModule], [], []),
  'addEssayTopic' : IDL.Func([IDL.Text, IDL.Text, EssayTopic], [], []),
  'addMCQ' : IDL.Func([IDL.Text, MCQ], [], []),
  'addModule' : IDL.Func([IDL.Text, Module], [], []),
  'addSubject' : IDL.Func([IDL.Text, Subject], [], []),
  'deleteEssayModule' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteEssayTopic' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'deleteMCQ' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteModule' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteSubject' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getEssayModules' : IDL.Func([], [IDL.Vec(EssayModule)], ['query']),
  'getEssayModulesByType' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(EssayModule)],
      ['query'],
    ),
  'getMCQs' : IDL.Func([], [IDL.Vec(MCQ)], ['query']),
  'getMCQsBySubject' : IDL.Func([IDL.Text], [IDL.Vec(MCQ)], ['query']),
  'getModules' : IDL.Func([], [IDL.Vec(Module)], ['query']),
  'getModulesBySubject' : IDL.Func([IDL.Text], [IDL.Vec(Module)], ['query']),
  'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'updateEssayModule' : IDL.Func([IDL.Text, EssayModule], [], []),
  'updateMCQ' : IDL.Func([IDL.Text, MCQ], [], []),
  'updateModule' : IDL.Func([IDL.Text, Module], [], []),
  'updateSubject' : IDL.Func([IDL.Text, Subject], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Id = IDL.Text;
  const EssayTopic = IDL.Record({ 'id' : Id, 'title' : IDL.Text });
  const EssayModule = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'moduleType' : IDL.Text,
    'topics' : IDL.Vec(EssayTopic),
  });
  const MCQ = IDL.Record({
    'id' : Id,
    'moduleId' : Id,
    'question' : IDL.Text,
    'explanation' : IDL.Text,
    'correctAnswer' : IDL.Text,
    'subjectId' : Id,
    'optionA' : IDL.Text,
    'optionB' : IDL.Text,
    'optionC' : IDL.Text,
    'optionD' : IDL.Text,
  });
  const Module = IDL.Record({
    'id' : Id,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'subjectId' : Id,
  });
  const Subject = IDL.Record({
    'id' : Id,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'color' : IDL.Text,
  });
  
  return IDL.Service({
    'addEssayModule' : IDL.Func([IDL.Text, EssayModule], [], []),
    'addEssayTopic' : IDL.Func([IDL.Text, IDL.Text, EssayTopic], [], []),
    'addMCQ' : IDL.Func([IDL.Text, MCQ], [], []),
    'addModule' : IDL.Func([IDL.Text, Module], [], []),
    'addSubject' : IDL.Func([IDL.Text, Subject], [], []),
    'deleteEssayModule' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteEssayTopic' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'deleteMCQ' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteModule' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteSubject' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getEssayModules' : IDL.Func([], [IDL.Vec(EssayModule)], ['query']),
    'getEssayModulesByType' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(EssayModule)],
        ['query'],
      ),
    'getMCQs' : IDL.Func([], [IDL.Vec(MCQ)], ['query']),
    'getMCQsBySubject' : IDL.Func([IDL.Text], [IDL.Vec(MCQ)], ['query']),
    'getModules' : IDL.Func([], [IDL.Vec(Module)], ['query']),
    'getModulesBySubject' : IDL.Func([IDL.Text], [IDL.Vec(Module)], ['query']),
    'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'updateEssayModule' : IDL.Func([IDL.Text, EssayModule], [], []),
    'updateMCQ' : IDL.Func([IDL.Text, MCQ], [], []),
    'updateModule' : IDL.Func([IDL.Text, Module], [], []),
    'updateSubject' : IDL.Func([IDL.Text, Subject], [], []),
  });
};

export const init = ({ IDL }) => { return []; };