/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Module {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'description' : string,
}
export interface Question {
  'id' : bigint,
  'explanation' : string,
  'correctAnswer' : bigint,
  'questionText' : string,
  'moduleCategory' : string,
  'options' : Array<string>,
}
export interface QuestionInput {
  'explanation' : string,
  'correctAnswer' : bigint,
  'questionText' : string,
  'moduleCategory' : string,
  'options' : Array<string>,
}
export interface QuizAttempt {
  'score' : bigint,
  'totalQuestions' : bigint,
  'moduleCategory' : string,
  'timestamp' : Time,
}
export type Time = bigint;
export interface _SERVICE {
  'addModule' : ActorMethod<[string, string, string], undefined>,
  'addQuestion' : ActorMethod<[QuestionInput], undefined>,
  'deleteQuestion' : ActorMethod<[bigint], undefined>,
  'getModule' : ActorMethod<[bigint], Module>,
  'getModules' : ActorMethod<[], Array<Module>>,
  'getQuestion' : ActorMethod<[bigint], Question>,
  'getQuestions' : ActorMethod<[], Array<Question>>,
  'getQuizAttempts' : ActorMethod<[], Array<QuizAttempt>>,
  'getTopScores' : ActorMethod<[], Array<bigint>>,
  'initialize' : ActorMethod<[string], undefined>,
  'isAdmin' : ActorMethod<[], boolean>,
  'submitQuiz' : ActorMethod<[bigint, bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];