/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface EssayModule {
  'id' : Id,
  'title' : string,
  'moduleType' : string,
  'topics' : Array<EssayTopic>,
}
export interface EssayTopic { 'id' : Id, 'title' : string }
export type Id = string;
export interface MCQ {
  'id' : Id,
  'moduleId' : Id,
  'question' : string,
  'explanation' : string,
  'correctAnswer' : string,
  'subjectId' : Id,
  'optionA' : string,
  'optionB' : string,
  'optionC' : string,
  'optionD' : string,
}
export interface Module {
  'id' : Id,
  'status' : string,
  'title' : string,
  'description' : string,
  'subjectId' : Id,
}
export interface Subject {
  'id' : Id,
  'icon' : string,
  'name' : string,
  'color' : string,
}
export interface _SERVICE {
  'addEssayModule' : ActorMethod<[string, EssayModule], undefined>,
  'addEssayTopic' : ActorMethod<[string, string, EssayTopic], undefined>,
  'addMCQ' : ActorMethod<[string, MCQ], undefined>,
  'addModule' : ActorMethod<[string, Module], undefined>,
  'addSubject' : ActorMethod<[string, Subject], undefined>,
  'deleteEssayModule' : ActorMethod<[string, string], undefined>,
  'deleteEssayTopic' : ActorMethod<[string, string, string], undefined>,
  'deleteMCQ' : ActorMethod<[string, string], undefined>,
  'deleteModule' : ActorMethod<[string, string], undefined>,
  'deleteSubject' : ActorMethod<[string, string], undefined>,
  'getEssayModules' : ActorMethod<[], Array<EssayModule>>,
  'getEssayModulesByType' : ActorMethod<[string], Array<EssayModule>>,
  'getMCQs' : ActorMethod<[], Array<MCQ>>,
  'getMCQsBySubject' : ActorMethod<[string], Array<MCQ>>,
  'getModules' : ActorMethod<[], Array<Module>>,
  'getModulesBySubject' : ActorMethod<[string], Array<Module>>,
  'getSubjects' : ActorMethod<[], Array<Subject>>,
  'updateEssayModule' : ActorMethod<[string, EssayModule], undefined>,
  'updateMCQ' : ActorMethod<[string, MCQ], undefined>,
  'updateModule' : ActorMethod<[string, Module], undefined>,
  'updateSubject' : ActorMethod<[string, Subject], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];