/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const QuestionInput = IDL.Record({
  'explanation' : IDL.Text,
  'correctAnswer' : IDL.Nat,
  'questionText' : IDL.Text,
  'moduleCategory' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const Module = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'description' : IDL.Text,
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'explanation' : IDL.Text,
  'correctAnswer' : IDL.Nat,
  'questionText' : IDL.Text,
  'moduleCategory' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const Time = IDL.Int;
export const QuizAttempt = IDL.Record({
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'moduleCategory' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'addModule' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addQuestion' : IDL.Func([QuestionInput], [], []),
  'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
  'getModule' : IDL.Func([IDL.Nat], [Module], []),
  'getModules' : IDL.Func([], [IDL.Vec(Module)], ['query']),
  'getQuestion' : IDL.Func([IDL.Nat], [Question], []),
  'getQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getQuizAttempts' : IDL.Func([], [IDL.Vec(QuizAttempt)], ['query']),
  'getTopScores' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'initialize' : IDL.Func([IDL.Text], [], []),
  'isAdmin' : IDL.Func([], [IDL.Bool], []),
  'submitQuiz' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const QuestionInput = IDL.Record({
    'explanation' : IDL.Text,
    'correctAnswer' : IDL.Nat,
    'questionText' : IDL.Text,
    'moduleCategory' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const Module = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'description' : IDL.Text,
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'explanation' : IDL.Text,
    'correctAnswer' : IDL.Nat,
    'questionText' : IDL.Text,
    'moduleCategory' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const Time = IDL.Int;
  const QuizAttempt = IDL.Record({
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'moduleCategory' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'addModule' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addQuestion' : IDL.Func([QuestionInput], [], []),
    'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
    'getModule' : IDL.Func([IDL.Nat], [Module], []),
    'getModules' : IDL.Func([], [IDL.Vec(Module)], ['query']),
    'getQuestion' : IDL.Func([IDL.Nat], [Question], []),
    'getQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getQuizAttempts' : IDL.Func([], [IDL.Vec(QuizAttempt)], ['query']),
    'getTopScores' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'initialize' : IDL.Func([IDL.Text], [], []),
    'isAdmin' : IDL.Func([], [IDL.Bool], []),
    'submitQuiz' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };