/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MCQ {
    id: Id;
    moduleId: Id;
    question: string;
    explanation: string;
    correctAnswer: string;
    subjectId: Id;
    optionA: string;
    optionB: string;
    optionC: string;
    optionD: string;
}
export interface EssayModule {
    id: Id;
    title: string;
    moduleType: string;
    topics: Array<EssayTopic>;
}
export interface EssayTopic {
    id: Id;
    title: string;
}
export interface Subject {
    id: Id;
    icon: string;
    name: string;
    color: string;
}
export interface Module {
    id: Id;
    status: string;
    title: string;
    description: string;
    subjectId: Id;
}
export type Id = string;
export interface backendInterface {
    addEssayModule(adminToken: string, em: EssayModule): Promise<void>;
    addEssayTopic(adminToken: string, moduleId: string, topic: EssayTopic): Promise<void>;
    addMCQ(adminToken: string, mcq: MCQ): Promise<void>;
    addModule(adminToken: string, mod: Module): Promise<void>;
    addSubject(adminToken: string, subject: Subject): Promise<void>;
    deleteEssayModule(adminToken: string, id: string): Promise<void>;
    deleteEssayTopic(adminToken: string, moduleId: string, topicId: string): Promise<void>;
    deleteMCQ(adminToken: string, id: string): Promise<void>;
    deleteModule(adminToken: string, id: string): Promise<void>;
    deleteSubject(adminToken: string, id: string): Promise<void>;
    getEssayModules(): Promise<Array<EssayModule>>;
    getEssayModulesByType(moduleType: string): Promise<Array<EssayModule>>;
    getMCQs(): Promise<Array<MCQ>>;
    getMCQsBySubject(subjectId: string): Promise<Array<MCQ>>;
    getModules(): Promise<Array<Module>>;
    getModulesBySubject(subjectId: string): Promise<Array<Module>>;
    getSubjects(): Promise<Array<Subject>>;
    updateEssayModule(adminToken: string, em: EssayModule): Promise<void>;
    updateMCQ(adminToken: string, mcq: MCQ): Promise<void>;
    updateModule(adminToken: string, mod: Module): Promise<void>;
    updateSubject(adminToken: string, subject: Subject): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addEssayModule(arg0: string, arg1: EssayModule): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEssayModule(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEssayModule(arg0, arg1);
            return result;
        }
    }
    async addEssayTopic(arg0: string, arg1: string, arg2: EssayTopic): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEssayTopic(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEssayTopic(arg0, arg1, arg2);
            return result;
        }
    }
    async addMCQ(arg0: string, arg1: MCQ): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMCQ(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMCQ(arg0, arg1);
            return result;
        }
    }
    async addModule(arg0: string, arg1: Module): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addModule(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addModule(arg0, arg1);
            return result;
        }
    }
    async addSubject(arg0: string, arg1: Subject): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSubject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSubject(arg0, arg1);
            return result;
        }
    }
    async deleteEssayModule(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEssayModule(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEssayModule(arg0, arg1);
            return result;
        }
    }
    async deleteEssayTopic(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEssayTopic(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEssayTopic(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteMCQ(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMCQ(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMCQ(arg0, arg1);
            return result;
        }
    }
    async deleteModule(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteModule(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteModule(arg0, arg1);
            return result;
        }
    }
    async deleteSubject(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubject(arg0, arg1);
            return result;
        }
    }
    async getEssayModules(): Promise<Array<EssayModule>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEssayModules();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEssayModules();
            return result;
        }
    }
    async getEssayModulesByType(arg0: string): Promise<Array<EssayModule>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEssayModulesByType(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEssayModulesByType(arg0);
            return result;
        }
    }
    async getMCQs(): Promise<Array<MCQ>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMCQs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMCQs();
            return result;
        }
    }
    async getMCQsBySubject(arg0: string): Promise<Array<MCQ>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMCQsBySubject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMCQsBySubject(arg0);
            return result;
        }
    }
    async getModules(): Promise<Array<Module>> {
        if (this.processError) {
            try {
                const result = await this.actor.getModules();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getModules();
            return result;
        }
    }
    async getModulesBySubject(arg0: string): Promise<Array<Module>> {
        if (this.processError) {
            try {
                const result = await this.actor.getModulesBySubject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getModulesBySubject(arg0);
            return result;
        }
    }
    async getSubjects(): Promise<Array<Subject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubjects();
            return result;
        }
    }
    async updateEssayModule(arg0: string, arg1: EssayModule): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEssayModule(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEssayModule(arg0, arg1);
            return result;
        }
    }
    async updateMCQ(arg0: string, arg1: MCQ): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMCQ(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMCQ(arg0, arg1);
            return result;
        }
    }
    async updateModule(arg0: string, arg1: Module): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateModule(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateModule(arg0, arg1);
            return result;
        }
    }
    async updateSubject(arg0: string, arg1: Subject): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubject(arg0, arg1);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
